spring.application.name=acg

spring.datasource.url=jdbc:mysql://localhost:3306/acg_merchandise?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



vaadin.dev-mode.enabled=true
vaadin.production-mode=false
vaadin.scan-packages=org.example.acg
vaadin.url-mapping=/


mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.example.acg.entity
mybatis.configuration.map-underscore-to-camel-case=true